config/routes.rb
Jobapp::Application.routes.draw do
  resources :questionnaires
match "/thanks(.:format)" => "questionnaires#thanks", :as => :thanks
   # get "questionnaires#thanks"
    root :to => 'questionnaires#new'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/questionnaire.rb
class Questionnaire < ActiveRecord::Base
  attr_accessible :date, :last_name, :first_name, :middle_name, :ssn, :related, :primary_contact_number, :secondary_contact_number, :work_school_different_name, :same_address_current_employee, :home_address, :zip_code, :how_long_at_address, :unemployment_periods, :employment_dates_and_company_names, :schools_during_unemployment, :work_for_cash, :report_cash_wages, :terminated_laid_off_details, :failed_drug_screen, :convicted_or_deferred_adjudication, :valid_drivers_license, :why_no_valid_dl, :license_clear, :years_driving_experience, :reliable_transporation, :refused_airport_badge, :check_list_physical_tasks, :check_list_work_environments, :email_address
  #serialize :check_list_physical_tasks, Array
  #serialize :check_list_work_environments, Array
  #erialize :values, Array
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  # def index
  #   @questionnaires = Questionnaire.all
  # end
  # 
  # def show
  #   @questionnaire = Questionnaire.find(params[:id])
  # end

  def new
    @questionnaire = Questionnaire.new
  end

  def create
    @questionnaire = Questionnaire.new(params[:questionnaire])
    if @questionnaire.save
      redirect_to thanks_path, :notice => "Successfully created questionnaire."
    else
      render :action => 'new'
    end
    # redirect_to root_url
  end
  
  def thanks
    
  end

  # def edit
  #    @questionnaire = Questionnaire.find(params[:id])
  #  end

  # def update
  #   @questionnaire = Questionnaire.find(params[:id])
  #   if @questionnaire.update_attributes(params[:questionnaire])
  #     redirect_to @questionnaire, :notice  => "Successfully updated questionnaire."
  #   else
  #     render :action => 'edit'
  #   end
  # end
  # 
  # def destroy
  #   @questionnaire = Questionnaire.find(params[:id])
  #   @questionnaire.destroy
  #   redirect_to questionnaires_url, :notice => "Successfully destroyed questionnaire."
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%#= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/questionnaires/_form.html.erb
<%= semantic_form_for @questionnaire do |f| %>
 <%= f.error_messages %>
	<%= f.inputs "Personal Information", :id => "personal" do %>
    <%= f.inputs :date, :first_name, :middle_name, :last_name %>
<%= f.input :email_address, :label => "Contact Email Address" %>
<%= f.input :ssn, :label => "SSN", :hint => "Social Security Number" %>
<%= f.input :related, :label => "Are you related to any current AccuFleet Employees?  If yes, list full name(s).", :as => :text, :input_html => { :class => 'autogrow', :rows => 3, :cols => 30, :maxlength => 250  } %>
<%= f.inputs :primary_contact_number, :secondary_contact_number %>
<% end %>
<%= f.inputs "Address Information", :id => "address" do %>
<%= f.input :work_school_different_name,  :label => "Have you ever been employed or attended school under a different name? If yes, what name?", :as => :text, :input_html => { :class => 'autogrow', :rows => 3, :cols => 30, :maxlength => 250  }  %>

<%= f.input :same_address_current_employee,  :label => "Do you live at the same address as any current AccuFleet Employees?  If yes, list full name(s).", :as => :text, :input_html => { :class => 'autogrow', :rows => 3, :cols => 30, :maxlength => 250  }  %>

<%= f.input :home_address,  :label => "Home Address", :as => :text, :input_html => { :class => 'autogrow', :rows => 5, :cols => 50, :maxlength => 250  }  %>
<%= f.input :zip_code %>
<%= f.input :how_long_at_address, :label => "How long have you lived at this address?", :as => :text, :input_html => { :class => 'autogrow', :rows => 1, :cols => 50, :maxlength => 250  } %>
<% end %>

<%= f.inputs "Employment Information", :id => "employment"  do %>
	<%= f.input :unemployment_periods, :label => "Do you have any periods of unemployment in the last 10 years? If yes, please explain with dates of unemployment. " %>
	<%= f.input :employment_dates_and_company_names, :label => "List employment dates and company names for ALL jobs held in the most recent 5 years" %>
	<%= f.input :schools_during_unemployment, :label => "Did you attend school during any unemployment periods? If Yes, please name school(s) attended. "%>
<% end %>
<%= f.inputs "Other", :id => "other" do  %>
<%= f.input :work_for_cash, :label => "Did you ever work and get paid in cash? " %>
<%= f.input :report_cash_wages, :label => "If yes, did you report your cash wages on your federal tax return?" %>
<%= f.input :terminated_laid_off_details, :label => "Have you ever been terminated or laid off from any of your previous employment positions? If yes, explain details for each. " %>
<%= f.input :failed_drug_screen, :label => "Have you ever failed a drug or alcohol test related to your employment or related to your driving? " %>
<%= f.input :convicted_or_deferred_adjudication, :label => "Have you ever been convicted or received deferred adjudication for a DUI, Misdemeanor or Felon? If yes, explain with dates. " %>
<% end %>
<%= f.inputs "Driving" do  %>
<%= f.input :valid_drivers_license, :label => "Do you have a valid driver's license?"%>
<%= f.input :why_no_valid_dl, :label => "If you do not have a valid driver's license at this time, explain why", :as => :text %>
<%= f.input :license_clear, :label => "Is your license clear of any citations/tickets for the past five years? If no, list ALL your citations/tickets from present to 2005. " %>
<%= f.input :years_driving_experience, :label => "How many years/months of driving experience do you have WITH a valid license? " %>
<%= f.input :reliable_transporation, :label => "Do you have reliable transportation to get to work?" %>
<% end %>
<%= f.input :refused_airport_badge, :label => "Have you ever been refused an airport security badge?" %>

<%= f.inputs "Physical Abilities & Environment", :id => "haveyouever"  do %>
<%= f.input :check_list_physical_tasks %>
<%= f.input :check_list_work_environments, :label => "Please review list and place a check next to all of the environments that would affect your ability to successfully perform a task. ", :as => :select, :collection => { "Heat (above 90 degrees F)" => "Heat (above 90 degrees F)","Cold (below 32 degrees F)" => "Cold (below 32 degrees F)","Rain" => "Rain","Snow" => "Snow","Fog" => "Fog","Nighttime (lack of light)" => "Nighttime (lack of light)","Direct Sunlight" => "Direct Sunlight","Noise (aircraft jet engines)" => "Noise (aircraft jet engines)","Chemicals (Allergies/Reactions)" => "Chemicals (Allergies/Reactions)","I have no issues with any of the above." => "I have no issues with any of the above." }, :input_html => { :multiple => true } %>

<% end %>
<%= f.buttons  %>
  <% end %>
 

app/views/questionnaires/edit.html.erb
<% title "Edit Questionnaire" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @questionnaire %> |
  <%= link_to "View All", questionnaires_path %>
</p>

app/views/questionnaires/index.html.erb
<% title "Questionnaires" %>

<table>
  <tr>
    <th>Date</th>
    <th>Last Name</th>
    <th>First Name</th>
    <th>Middle Name</th>
    <th>Ssn</th>
    <th>Related</th>
    <th>Primary Contact Number</th>
    <th>Secondary Contact Number</th>
    <th>Work School Different Name</th>
    <th>Same Address Current Employee</th>
    <th>Home Address</th>
    <th>Zip Code</th>
    <th>How Long At Address</th>
    <th>Unemployment Periods</th>
    <th>Employment Dates And Company Names</th>
    <th>Schools During Unemployment</th>
    <th>Work For Cash</th>
    <th>Report Cash Wages</th>
    <th>Terminated Laid Off Details</th>
    <th>Failed Drug Screen</th>
    <th>Convicted Or Deferred Adjudication</th>
    <th>Valid Drivers License</th>
    <th>Why No Valid Dl</th>
    <th>License Clear</th>
    <th>Years Driving Experience</th>
    <th>Reliable Transporation</th>
    <th>Refused Airport Badge</th>
    <th>Check List Physical Tasks</th>
    <th>Check List Work Environments</th>
    <th>Email Address</th>
  </tr>
  <% for questionnaire in @questionnaires %>
    <tr>
      <td><%= questionnaire.date %></td>
      <td><%= questionnaire.last_name %></td>
      <td><%= questionnaire.first_name %></td>
      <td><%= questionnaire.middle_name %></td>
      <td><%= questionnaire.ssn %></td>
      <td><%= questionnaire.related %></td>
      <td><%= questionnaire.primary_contact_number %></td>
      <td><%= questionnaire.secondary_contact_number %></td>
      <td><%= questionnaire.work_school_different_name %></td>
      <td><%= questionnaire.same_address_current_employee %></td>
      <td><%= questionnaire.home_address %></td>
      <td><%= questionnaire.zip_code %></td>
      <td><%= questionnaire.how_long_at_address %></td>
      <td><%= questionnaire.unemployment_periods %></td>
      <td><%= questionnaire.employment_dates_and_company_names %></td>
      <td><%= questionnaire.schools_during_unemployment %></td>
      <td><%= questionnaire.work_for_cash %></td>
      <td><%= questionnaire.report_cash_wages %></td>
      <td><%= questionnaire.terminated_laid_off_details %></td>
      <td><%= questionnaire.failed_drug_screen %></td>
      <td><%= questionnaire.convicted_or_deferred_adjudication %></td>
      <td><%= questionnaire.valid_drivers_license %></td>
      <td><%= questionnaire.why_no_valid_dl %></td>
      <td><%= questionnaire.license_clear %></td>
      <td><%= questionnaire.years_driving_experience %></td>
      <td><%= questionnaire.reliable_transporation %></td>
      <td><%= questionnaire.refused_airport_badge %></td>
      <td><%= questionnaire.check_list_physical_tasks %></td>
      <td><%= questionnaire.check_list_work_environments %></td>
      <td><%= questionnaire.email_address %></td>
      <td><%= link_to "Show", questionnaire %></td>
      <td><%= link_to "Edit", edit_questionnaire_path(questionnaire) %></td>
      <td><%= link_to "Destroy", questionnaire, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Questionnaire", new_questionnaire_path %></p>

app/views/questionnaires/new.html.erb
<% title "New Questionnaire" %>

<%= render 'form' %>

<p><%#= link_to "Back to List", questionnaires_path %></p>

app/views/questionnaires/show.html.erb
<% title "Questionnaire" %>

<p>
  <strong>Date:</strong>
  <%= @questionnaire.date %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @questionnaire.last_name %>
</p>
<p>
  <strong>First Name:</strong>
  <%= @questionnaire.first_name %>
</p>
<p>
  <strong>Middle Name:</strong>
  <%= @questionnaire.middle_name %>
</p>
<p>
  <strong>Ssn:</strong>
  <%= @questionnaire.ssn %>
</p>
<p>
  <strong>Related:</strong>
  <%= @questionnaire.related %>
</p>
<p>
  <strong>Primary Contact Number:</strong>
  <%= @questionnaire.primary_contact_number %>
</p>
<p>
  <strong>Secondary Contact Number:</strong>
  <%= @questionnaire.secondary_contact_number %>
</p>
<p>
  <strong>Work School Different Name:</strong>
  <%= @questionnaire.work_school_different_name %>
</p>
<p>
  <strong>Same Address Current Employee:</strong>
  <%= @questionnaire.same_address_current_employee %>
</p>
<p>
  <strong>Home Address:</strong>
  <%= @questionnaire.home_address %>
</p>
<p>
  <strong>Zip Code:</strong>
  <%= @questionnaire.zip_code %>
</p>
<p>
  <strong>How Long At Address:</strong>
  <%= @questionnaire.how_long_at_address %>
</p>
<p>
  <strong>Unemployment Periods:</strong>
  <%= @questionnaire.unemployment_periods %>
</p>
<p>
  <strong>Employment Dates And Company Names:</strong>
  <%= @questionnaire.employment_dates_and_company_names %>
</p>
<p>
  <strong>Schools During Unemployment:</strong>
  <%= @questionnaire.schools_during_unemployment %>
</p>
<p>
  <strong>Work For Cash:</strong>
  <%= @questionnaire.work_for_cash %>
</p>
<p>
  <strong>Report Cash Wages:</strong>
  <%= @questionnaire.report_cash_wages %>
</p>
<p>
  <strong>Terminated Laid Off Details:</strong>
  <%= @questionnaire.terminated_laid_off_details %>
</p>
<p>
  <strong>Failed Drug Screen:</strong>
  <%= @questionnaire.failed_drug_screen %>
</p>
<p>
  <strong>Convicted Or Deferred Adjudication:</strong>
  <%= @questionnaire.convicted_or_deferred_adjudication %>
</p>
<p>
  <strong>Valid Drivers License:</strong>
  <%= @questionnaire.valid_drivers_license %>
</p>
<p>
  <strong>Why No Valid Dl:</strong>
  <%= @questionnaire.why_no_valid_dl %>
</p>
<p>
  <strong>License Clear:</strong>
  <%= @questionnaire.license_clear %>
</p>
<p>
  <strong>Years Driving Experience:</strong>
  <%= @questionnaire.years_driving_experience %>
</p>
<p>
  <strong>Reliable Transporation:</strong>
  <%= @questionnaire.reliable_transporation %>
</p>
<p>
  <strong>Refused Airport Badge:</strong>
  <%= @questionnaire.refused_airport_badge %>
</p>
<p>
  <strong>Check List Physical Tasks:</strong>
  <%= @questionnaire.check_list_physical_tasks %>
</p>
<p>
  <strong>Check List Work Environments:</strong>
  <%= @questionnaire.check_list_work_environments %>
</p>
<p>
  <strong>Email Address:</strong>
  <%= @questionnaire.email_address %>
</p>

<p>
  <%= link_to "Edit", edit_questionnaire_path(@questionnaire) %> |
  <%= link_to "Destroy", @questionnaire, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", questionnaires_path %>
</p>

app/views/questionnaires/thanks.html.erb
<h1>Thank You for completing AccuFleet's Applicant Questionnaire.</h1> <p> All questionnaires will be reviewed and the most qualified candidates will be contacted with further information.
</p>